USE [BIT]
GO

/****** Object:  StoredProcedure [dbo].[00_ART]    Script Date: 3/6/2025 10:27:46 AM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE PROCEDURE [dbo].[00_ART]
			@RESPONSE nvarchar(50) OUTPUT,
			@SOLICITUD nvarchar(50)=null,
			@PUBLICACION int=null,
			@EDICION int=null,
			@FILAS_AFECTADAS INTEGER=null,
			@FOLIO NVARCHAR(50)=null,
			@FECHA_SEMAFORO NVARCHAR(50)=null
		AS BEGIN
			SET NOCOUNT ON; --PARA PODER HACER ROWCOUNT
			IF(@SOLICITUD='SALIDAS_PREMIOS') --PARASITO EN ESTE PROCEDIMIENTO PARA NO HACER OTRO, ES PARA LA SALIDA DE PREMIOS AL PVWIN - 11/06/2020 - 10:06:56 a. m.
				BEGIN
					--VARIABLES
						SET @FOLIO = (SELECT CONCAT('TS', RIGHT(REPLICATE('0', 7) + LEFT((SELECT TOP 1 NTRASAL AS REFERENCIA FROM PVWIN...SEMAFORO ORDER BY F_ULT_ACT DESC),8), 8)))
						SET @FECHA_SEMAFORO = (SELECT TOP 1 F_ULT_ACT AS REFERENCIA FROM PVWIN...SEMAFORO ORDER BY F_ULT_ACT DESC)
					--INSERT DEL MOVIMIENTO AL PVWIN
						INSERT INTO [MASTER].[dbo].[MOVANIO]
							(
								TRANSAC,
								REFERENCIA,
								F_MOVIM,
								CAJERO,
								ARTICULO,
								DESC_MOV,
								CANTIDAD,
								F_ULT_ACT,
								H_ULT_ACT,
								U_ULT_ACT,
								DESCRIP
							)
						SELECT
							SALIDAS_PREMIOS.*,
							ARTICULO.DESCRIPCION
						FROM
							(
								SELECT
									'ts' AS TRANSAC,
									@FOLIO AS REFERENCIA,
									GETDATE() AS F_MOVIM,
									SUBSTRING (USUARIO ,0 , 9)  AS CAJERO,
									ARTICULO AS ARTICULO,
									CONCAT('CANJEOS PORTAL ',FOLIO) AS DESC_MOV,
									CANTIDAD AS CANTIDAD,
									GETDATE() AS F_ULT_ACT,
									CONVERT(VARCHAR(8),getdate(),108) AS H_ULT_ACT,
									SUBSTRING (USUARIO ,0 , 9) AS U_ULT_ACT
								FROM [BIT].[DBO].[SALIDAS_PREMIOS]
								WHERE EDICION = 1
							)SALIDAS_PREMIOS
						LEFT JOIN
							(
								SELECT ARTICULO, DESCRIPCION FROM [BIT].[DBO].[V_ART]
							)ARTICULO
						ON SALIDAS_PREMIOS.ARTICULO = ARTICULO.ARTICULO
					--PARA VER SI SE TIENE QUE MOVER EL FOLIO SOLO EN CASO DE QUE SI SE INSERTARON FILAS
						SET @FILAS_AFECTADAS = @@ROWCOUNT
					--PROCEDE SOLO SI SE DIO SALIDA
						IF(@FILAS_AFECTADAS > 0)BEGIN
							--UPDATE DE LA EXISTENCIA AL ARTICULO DEL PVWIN
								UPDATE PVWIN
									SET
										TSA_MF = ISNULL(TSA_MF,0) + SALIDAS_PREMIOS.CANTIDAD,
										TSA_AF = ISNULL(TSA_AF,0) + SALIDAS_PREMIOS.CANTIDAD
								FROM
									(
										--ASI NO FUNCIONA EL UPDATE MARCAR ERROR DE QUE ES DEMASIADO COMPLEJO
											--SELECT
											--	ARTICULO,
											--	SAL_MF,
											--	SAL_AF
											--FROM PVWIN...ARTICULO
											--WHERE GRUPO = 'PRE'
										SELECT *
										FROM OPENROWSET(
											'Microsoft.ACE.OLEDB.12.0',
											'dBase 5.0;Database=C:\_PVW\001',
											'SELECT
												ARTICULO,
												TSA_MF,
												TSA_AF
											FROM ARTICULO
											WHERE GRUPO = ''PRE'''
										)
									)PVWIN
								LEFT JOIN
									(
										SELECT
											ARTICULO,
											SUM(CANTIDAD) AS CANTIDAD
										FROM
											[BIT].[DBO].[SALIDAS_PREMIOS]
										WHERE EDICION = 1
										GROUP BY ARTICULO
									)SALIDAS_PREMIOS
								ON PVWIN.ARTICULO = SALIDAS_PREMIOS.ARTICULO
								WHERE SALIDAS_PREMIOS.CANTIDAD IS NOT NULL
							--MARCA DE QUE YA SE DIO SALIDA
								UPDATE [BIT].[DBO].[SALIDAS_PREMIOS]
									SET
										EDICION = 2
									WHERE EDICION = 1
							--PARA ACTUALIZAR FOLIO DE TRASPASO EN EL SEMAFORO DE PVWIN
								UPDATE PVWIN...SEMAFORO SET NTRASAL = (SELECT NTRASAL FROM PVWIN...SEMAFORO  WHERE F_ULT_ACT = @FECHA_SEMAFORO) +  1
							--ESPUESTA DE TZITO
								SELECT @RESPONSE = @FILAS_AFECTADAS
						END
						IF(@FILAS_AFECTADAS = 0)BEGIN
							--ESPUESTA DE TZITO
								SELECT @RESPONSE = 'SIN FILAS AFECTADAS'
						END
				END
			IF(@SOLICITUD='CORRECCION_NEGATIVOS_PREMIOS') --PARASITO EN ESTE PROCEDIMIENTO PARA NO HACER OTRO, ES PARA HACER UN TRASPASO PARA CORREGIR LOS NEGATIVOS EN PREMIOS - 22/06/2020 - 09:56:38 a. m.
				BEGIN
					--VARIABLES
						SET @FOLIO = (SELECT CONCAT('TE', RIGHT(REPLICATE('0', 7) + LEFT((SELECT TOP 1 NTRAENT AS REFERENCIA FROM PVWIN...SEMAFORO ORDER BY F_ULT_ACT DESC),8), 8)))
						SET @FECHA_SEMAFORO = (SELECT TOP 1 F_ULT_ACT AS REFERENCIA FROM PVWIN...SEMAFORO ORDER BY F_ULT_ACT DESC)
					--INSERT DEL MOVIMIENTO AL PVWIN
						INSERT INTO [MASTER].[dbo].[MOVANIO]
							(
								TRANSAC,
								REFERENCIA,
								F_MOVIM,
								CAJERO,
								ARTICULO,
								DESC_MOV,
								CANTIDAD,
								F_ULT_ACT,
								H_ULT_ACT,
								U_ULT_ACT,
								DESCRIP
							)
						SELECT
							AJUSTE.*,
							ARTICULO.DESCRIPCION
						FROM
							(
								SELECT
									'te' AS TRANSAC,
									@FOLIO AS REFERENCIA,
									GETDATE() AS F_MOVIM,
									'PORTALFT' AS CAJERO,
									ARTICULO AS ARTICULO,
									'CORRECCION DE NEGATIVOS' AS DESC_MOV,
									-(EXISTENCIA) AS CANTIDAD,
									GETDATE() AS F_ULT_ACT,
									CONVERT(VARCHAR(8),getdate(),108) AS H_ULT_ACT,
									'PORTALFT' AS U_ULT_ACT
								FROM [BIT].[DBO].[V_ART] WHERE EXISTENCIA < 0
								AND GRUPO IN ('PRE')
							)AJUSTE
						LEFT JOIN
							(
								SELECT ARTICULO, DESCRIPCION FROM [BIT].[DBO].[V_ART]
							)ARTICULO
						ON AJUSTE.ARTICULO = ARTICULO.ARTICULO
					--PARA VER SI SE TIENE QUE MOVER EL FOLIO SOLO EN CASO DE QUE SI SE INSERTARON FILAS
						SET @FILAS_AFECTADAS = @@ROWCOUNT
					--PROCEDE SOLO SI SE DIO SALIDA
						IF(@FILAS_AFECTADAS > 0)BEGIN
							--UPDATE DE LA EXISTENCIA AL ARTICULO DEL PVWIN
								UPDATE PVWIN
									SET
										TEN_MF = ISNULL(TEN_MF,0) + AJUSTE_PREMIOS.CANTIDAD,
										TEN_AF = ISNULL(TEN_AF,0) + AJUSTE_PREMIOS.CANTIDAD
								FROM
									(
										--ASI NO FUNCIONA EL UPDATE MARCAR ERROR DE QUE ES DEMASIADO COMPLEJO
											--SELECT
											--	ARTICULO,
											--	SAL_MF,
											--	SAL_AF
											--FROM PVWIN...ARTICULO
											--WHERE GRUPO = 'PRE'
										SELECT *
										FROM OPENROWSET(
											'Microsoft.ACE.OLEDB.12.0',
											'dBase 5.0;Database=C:\_PVW\001',
											'SELECT
												ARTICULO,
												TEN_MF,
												TEN_AF
											FROM ARTICULO
											WHERE GRUPO = ''PRE'''
										)
									)PVWIN
								LEFT JOIN
									(
										SELECT
											ARTICULO,
											-(SUM(EXISTENCIA)) AS CANTIDAD
										FROM [BIT].[DBO].[V_ART] WHERE EXISTENCIA < 0
										AND GRUPO IN ('PRE')
										GROUP BY ARTICULO
									)AJUSTE_PREMIOS
								ON PVWIN.ARTICULO = AJUSTE_PREMIOS.ARTICULO
								WHERE AJUSTE_PREMIOS.CANTIDAD IS NOT NULL
							--PARA ACTUALIZAR FOLIO DE TRASPASO EN EL SEMAFORO DE PVWIN
								UPDATE PVWIN...SEMAFORO SET NTRAENT = (SELECT NTRAENT FROM PVWIN...SEMAFORO  WHERE F_ULT_ACT = @FECHA_SEMAFORO) +  1
							--ESPUESTA DE TZITO
								SELECT @RESPONSE = @FILAS_AFECTADAS
						END
						IF(@FILAS_AFECTADAS = 0)BEGIN
							--ESPUESTA DE TZITO
								SELECT @RESPONSE = 'SIN FILAS AFECTADAS'
						END
				END
			IF(@SOLICITUD='APLICAR_PUBLICACION')	--APLICACION DE PUBLICACIONES EN PVWIN DE SUCURSALES SEGUN ART Y No. DE PUBLICACION 10/08/2018 - 06:55:38 A.M.
				BEGIN
					IF(@PUBLICACION IS NOT NULL AND @PUBLICACION != '')
					BEGIN
						EXECUTE
							('
								UPDATE PVWIN
								SET
									--PVWIN.PCIO_COM = ISNULL(ART.PCIO_COM, PVWIN.PCIO_COM),
									PVWIN.PCIO_VTA = ISNULL(ART.PCIO_VTA, PVWIN.PCIO_VTA),
									PVWIN.DESCUENTO = ISNULL(ART.DESCUENTO, PVWIN.DESCUENTO),
									PVWIN.VIGENCIA = ISNULL(ART.VIGENCIA, PVWIN.VIGENCIA),
									PVWIN.CADUCIDAD = ISNULL(ART.CADUCIDAD, PVWIN.CADUCIDAD)
								FROM
									(
										SELECT * FROM [BIT].[dbo].[ART]
										WHERE PUBLICACION = '+@PUBLICACION+'
									)ART
								LEFT JOIN
									(
										SELECT *
										FROM OPENROWSET(
											''Microsoft.ACE.OLEDB.12.0'',
											''dBase 5.0;Database=C:\_PVW\001'',
											''SELECT * FROM ARTICULO''
										)
									)PVWIN
								ON ART.ARTICULO = PVWIN.ARTICULO
							')
					END
					SELECT @RESPONSE = 'ETZITO'
				END
			IF(@SOLICITUD='APLICAR_EDICION_MIN_MAX')	--APLICACION DE EDICION_MIN_MAX EN PVWWIN DE SUCURSALES SEGUN ART Y No. DE EDICION 10/08/2018 - 06:55:38 A.M.
				BEGIN
					IF(@EDICION IS NOT NULL AND @EDICION != '')
					BEGIN
						EXECUTE
							('
								UPDATE PVWIN
								SET
									PVWIN.MINIMO = ISNULL(EDICION.MINIMO, PVWIN.MINIMO),
									PVWIN.MAXIMO = ISNULL(EDICION.MAXIMO, PVWIN.MAXIMO)
								FROM
									(
										SELECT * FROM [BIT].[dbo].[MOV]
										WHERE FOLIO = '+@EDICION+'
									)EDICION
								LEFT JOIN
									(
										SELECT *
										FROM OPENROWSET(
											''Microsoft.ACE.OLEDB.16.0'',
											''dBase 5.0;Database=C:\_PVW\001'',
											''SELECT * FROM ARTICULO''
										)
									)PVWIN
								ON EDICION.ARTICULO = PVWIN.ARTICULO
							')
					END
					SELECT @RESPONSE = 'ETZITO'
				END
		END
GO
-- puede afectar la version del provider oledb 12 o 16

