-- VISTAS PARA EL PVWIN
-- ! NOTA: SI ES NUEVO SERVIDOR RECUERDA HACER PROCEDIMIENTO ALMACENADO DEL ARCHIVO: 00_ART.sql ("SIRVE PARA APLICAR_EDICION_MIN_MAX, SALIDAS_PREMIOS, CORRECCION_NEGATIVOS_PREMIOS Y APLICAR_PUBLICACION")
--//////////////////////////////////////////////////////////////////////////////////////////
--*PARA HABILITAR AD HOC DISTRIBUTED QUERIES EN EL SERVIDOR***************
	sp_configure 'show advanced options', 1;
	RECONFIGURE;
	GO
	sp_configure 'Ad Hoc Distributed Queries', 1;
	RECONFIGURE;
	GO
--************************************************************************
--*VISTAS TEMPORALES EN MASTER PARA ANTIGUAS PROGRAMACIONES***************
USE MASTER
	--- YA ESTUBO BUENO CON EL ASTERISCO AL MENOS PARA EL ARTICULO - 30/11/2023 11:23:04 AM
		DROP VIEW ARTICULO
		GO
		-- CREATE VIEW ARTICULO AS SELECT * FROM PVWIN...ARTICULO
		-- GO
		CREATE VIEW ARTICULO AS SELECT
			ARTICULO,
			C_UNIDAD,
			ALTERNA,
			PRODSERV,
			DESCRIP,
			UDEM_C,
			UDEM,
			TIPO,
			FACTOR,
			GRUPO,
			DEPTO,
			LOCALIZA,
			LOCALIZA2,
			DECIMALES,
			MINIMO,
			MAXIMO,
			DOLARES,
			DOLAR_INI,
			COMIVA,
			VTAIVA,
			PCIO_ULT,
			PCIO_COM,
			MARGEN,
			MARGEN2,
			MARGEN3,
			MARGEN4,
			PCIO_VTA,
			PCIO_VTA2,
			PCIO_VTA3,
			PCIO_VTA4,
			VOLUMEN,
			VOLUMEN1,
			VOLUMEN2,
			VOLUMEN3,
			VOLUMEN4,
			PCIO_PRO,
			PCIO_INI,
			CAMBIO,
			EXENTO,
			IEPS,
			IVA,
			LIBRE,
			LIBRE_NUM,
			LIBRE_FAC,
			LIBRE_DIV,
			PROMO,
			DESCUENTO,
			VIGENCIA,
			CADUCIDAD,
			IMAGEN,
			INV_INI,
			REGISTRADO,
			VTA_PRO_AF,
			F_INV_INI,
			F_ULT_ENT,
			F_ULT_SAL,
			F_ULT_AJU,
			F_ULT_DEV,
			F_ULT_TRA,
			EXISTENCIA,
			ENT_MF,
			SAL_MF,
			AJU_MF,
			DVC_MF,
			DVP_MF,
			TEN_MF,
			TSA_MF,
			ENT_AF,
			SAL_AF,
			AJU_AF,
			DVC_AF,
			DVP_AF,
			TEN_AF,
			TSA_AF,
			COM_MF,
			IEP_C_MF,
			IVA_C_MF,
			VTA_MF,
			IEP_V_MF,
			IVA_V_MF,
			C_VTA_MF,
			VAR_MF,
			IDVC_MF,
			IEP_DVC_MF,
			IVA_DVC_MF,
			C_DVC_MF,
			IDVP_MF,
			IEP_DVP_MF,
			IVA_DVP_MF,
			C_DVP_MF,
			ITEN_MF,
			C_TEN_MF,
			ITSA_MF,
			C_TSA_MF,
			COM_AF,
			IEP_C_AF,
			IVA_C_AF,
			VTA_AF,
			IEP_V_AF,
			IVA_V_AF,
			C_VTA_AF,
			VAR_AF,
			IDVC_AF,
			IEP_DVC_AF,
			IVA_DVC_AF,
			C_DVC_AF,
			IDVP_AF,
			IEP_DVP_AF,
			IVA_DVP_AF,
			C_DVP_AF,
			ITEN_AF,
			C_TEN_AF,
			ITSA_AF,
			C_TSA_AF,
			PORC_UTIL,
			LINCOM,
			NUM_ETI,
			BAJA,
			PESOKGM,
			PELIGRO,
			F_ULT_ACT,
			H_ULT_ACT,
			U_ULT_ACT,
			ETIBUS,
			PEDIMEN,
			ADUANA,
			FECHPED,
			IDPV
		FROM PVWIN...ARTICULO
		GO
	--- ///////////////////////////////// -
	--- YA ESTUBO BUENO CON EL ASTERISCO AHORA PARA MOVANIO - 29/10/2024 11:38:18 AM
		DROP VIEW MOVANIO
		GO
		CREATE VIEW MOVANIO AS SELECT
			TRANSAC,
			SERIE,
			REFERENCIA,
			F_MOVIM,
			UUID,
			CAJERO,
			ARTICULO,
			ART_PRO,
			DESCRIP,
			TIPO,
			AGENTE,
			CLI_PRO,
			NOMBRE,
			DESC_MOV,
			C_UDEM_C,
			CANTIDAD,
			FACTOR,
			PCIO_COM,
			PCIO_PRO,
			PCIO_VTA,
			PCIO_DES,
			PG_GLOBAL,
			REGLA,
			CAMBIO,
			NPRECIO,
			DOLAR,
			EXENTO,
			IEPS,
			IVA,
			PORCENT,
			ANTEXIS,
			ULTEXIS,
			IMP_P_COM,
			IMP_P_PRO,
			IMP_P_VTA,
			IMP_VTA,
			IMP_DESC,
			IMP_IEPS,
			IMP_IVA,
			ISR_RET,
			IVA_RET,
			TERMINAL,
			VENBSC,
			FP_EF,
			FP_DL,
			FP_TJ,
			FP_CH,
			FP_VL,
			FP_NT,
			FP_PY,
			FP_NI,
			FP_CR,
			FPAGO,
			REGS,
			FACTURAR,
			TAGTERM,
			FLAG,
			EXPORTAR,
			EXPTERM,
			F_FACEMI,
			ANULACMS,
			F_ULT_ACT,
			U_ULT_ACT,
			H_ULT_ACT,
			COMENTVTA
		FROM PVWIN...MOVANIO
		GO
	--- ///////////////////////////////// -
	--- RESTO DE VISTAS - 29/10/2024 11:39:54 AM
		DROP VIEW USUARIOS
		GO
		CREATE VIEW USUARIOS AS SELECT * FROM PVWIN...USUARIOS
		GO
		DROP VIEW CAJAS
		GO
		CREATE VIEW CAJAS AS SELECT * FROM PVWIN...CAJAS
		GO
		DROP VIEW ABONOS
		GO
		CREATE VIEW ABONOS AS SELECT * FROM PVWIN...ABONOS
		GO
		DROP VIEW CLIENTES
		GO
		CREATE VIEW CLIENTES AS SELECT * FROM PVWIN...CLIENTES
		GO
		DROP VIEW PROVEEDORES
		GO
		CREATE VIEW PROVEEDORES AS SELECT * FROM PVWIN...PROVEED
		GO
		DROP VIEW GENERAL
		GO
		CREATE VIEW GENERAL AS SELECT * FROM PVWIN...GENERAL
		GO
		DROP VIEW SEMAFORO
		GO
		CREATE VIEW SEMAFORO AS SELECT * FROM PVWIN...SEMAFORO
		GO
		--*08/03/2022 01:09:51 PM
			DROP VIEW AUTOTRAN
			GO
			CREATE VIEW AUTOTRAN AS SELECT * FROM PVWIN...AUTOTRAN
			GO
			DROP VIEW FIGTRANS
			GO
			CREATE VIEW FIGTRANS AS SELECT * FROM PVWIN...FIGTRANS
			GO
	--- ///////////////////////////////// -
--*NUEVAS VISTAS BIT******************************************************
USE BIT
	DROP VIEW ARTICULO
	GO
	CREATE VIEW ARTICULO AS SELECT * FROM PVWIN...ARTICULO
	GO
	DROP VIEW MOVANIO
	GO
	CREATE VIEW MOVANIO AS SELECT * FROM PVWIN...MOVANIO
	GO
	DROP VIEW USUARIOS
	GO
	CREATE VIEW USUARIOS AS SELECT * FROM PVWIN...USUARIOS
	GO
	DROP VIEW CAJAS
	GO
	CREATE VIEW CAJAS AS SELECT * FROM PVWIN...CAJAS
	GO
	DROP VIEW ABONOS
	GO
	CREATE VIEW ABONOS AS SELECT * FROM PVWIN...ABONOS
	GO
	DROP VIEW CLIENTES
	GO
	CREATE VIEW CLIENTES AS SELECT * FROM PVWIN...CLIENTES
	GO
	DROP VIEW PROVEEDORES
	GO
	CREATE VIEW PROVEEDORES AS SELECT * FROM PVWIN...PROVEED
	GO
	DROP VIEW GENERAL
	GO
	CREATE VIEW GENERAL AS SELECT * FROM PVWIN...GENERAL
	GO
	DROP VIEW SEMAFORO
	GO
	CREATE VIEW SEMAFORO AS SELECT * FROM PVWIN...SEMAFORO
	GO
	--*08/03/2022 01:09:51 PM
		DROP VIEW AUTOTRAN
		GO
		CREATE VIEW AUTOTRAN AS SELECT * FROM PVWIN...AUTOTRAN
		GO
		DROP VIEW FIGTRANS
		GO
		CREATE VIEW FIGTRANS AS SELECT * FROM PVWIN...FIGTRANS
		GO

--*PARA UTILIZAR PVWIN COMO BASE******************************************
--NOTA: VISTAS PARA EL CASO DONDE LA SUCURSAL OPERE CON PVWIN, PARA LAS QUE OPEREN CON "BIT-PAULINA" SE CREARAN LAS BASES CORRESPONDIENTES"
	USE [BIT]
	DROP VIEW V_ART
	GO
	CREATE VIEW V_ART AS
		SELECT
			[ARTICULO] AS [ARTICULO],
			REPLACE(DESCRIP,'Ð','Ñ') AS [DESCRIPCION],
			[F_ULT_ACT] AS [FECHA_HORA],
			[GRUPO],
			[DEPTO],
			[LOCALIZA] AS [LOCALIZACION],
			[MINIMO] AS [MINIMO],
			[MAXIMO] AS [MAXIMO],
			[FACTOR] AS [FACTOR],
			+IIF([INV_INI] IS NULL,0,[INV_INI])+IIF([ENT_MF] IS NULL,0,[ENT_MF])-IIF([SAL_MF] IS NULL,0,[SAL_MF])+IIF([AJU_MF] IS NULL,0,[AJU_MF])
			+IIF([DVC_MF] IS NULL,0,[DVC_MF])-IIF([DVP_MF] IS NULL,0,[DVP_MF])+IIF([TEN_MF] IS NULL,0,[TEN_MF])-IIF([TSA_MF] IS NULL,0,[TSA_MF])
				AS [EXISTENCIA],
			[PCIO_COM] AS [PCIO_COM],
			[PCIO_VTA] AS [PCIO_VTA],
			[MARGEN] AS [MARGEN],
			ROUND(
					ISNULL([PCIO_COM],0)+
					(ISNULL([PCIO_COM],0)*ISNULL([IVA],0)/100)+
					((ISNULL([PCIO_COM],0)+ISNULL([PCIO_COM],0)*ISNULL([IVA],0)/100)*ISNULL([IEPS],0)/100)
					,2) AS [PRECIO_COMPRA_NETO],
				ROUND(
					ISNULL([PCIO_VTA],0)+
					(ISNULL([PCIO_VTA],0)*ISNULL([IVA],0)/100)+
					((ISNULL([PCIO_VTA],0)+ISNULL([PCIO_VTA],0)*ISNULL([IVA],0)/100)*ISNULL([IEPS],0)/100)
					,2) AS [PRECIO_VENTA_NETO],
			[IVA] AS [IVA],
			[IEPS] AS [IEPS],
			[DESCUENTO] AS [DESCUENTO],
			IIF(CADUCIDAD>=(SELECT CONVERT (date, SYSDATETIME()))
				AND[VIGENCIA]<=(SELECT CONVERT (date, SYSDATETIME())),
					(
						ROUND([PCIO_VTA]*(1+[IEPS]/100+[IEPS]*[IVA]/10000+[IVA]/100)*[DESCUENTO]/100,1)
					),0
				)AS [TOTAL_DESCUENTO],
			[VIGENCIA],
			[CADUCIDAD],
			SAL_MF,
			SAL_AF
		FROM PVWIN...ARTICULO
	GO