---ACTUALIZAR RESPALDOS PVWIN--
USE BIT
EXEC [00_UTILERIAS]
@SOLICITUD = 'RESPALDAR_PVWIN',
@EMPRESA = 'FT',
@SUCURSAL_PVWIN = 'CENTRO'


--PARA REVISAR SI SE ACTUALIZO--
SELECT *
  FROM [FT_CENTRO].[dbo].[PVWIN_MOVANIO]
  ORDER BY F_MOVIM DESC,H_ULT_ACT DESC