---PARA IMPORTAR PROVEDORES QUE NO ESTAN EN SFT DESDE PVWIN DE BODEGA
	--HECHA POR MOSQUI EL 09/10/2019 - 11:29:54 A. M.
	INSERT INTO [FT].[dbo].[IDENTIDADES]
		(
			TIPO,
			ID_PROV,
			NOMBRE,
			CALLE,
			NUMERO,
			INTERIOR,
			COLONIA,
			MUNICIPIO,
			CIUDAD,
			ESTADO,
			PAIS,
			CP,
			TELEFONO1,
			RFC,
			EMAIL
		)
	SELECT 
		'PROVEEDOR' AS TIPO,
		A.PROVEED,
		A.NOMBRE,
		A.DIRECCION,
		A.NUMEXT,
		A.NUMINT,
		A.COLONIA, 
		A.MUNICIPIO, 
		A.CIUDAD, 
		A.ESTADO, 
		A.PAIS, 
		A.COD_POST, 
		A.TELEFONO,   
		A.RFC, 
		A.EMAIL   
	FROM   
		(
			SELECT * FROM [10.10.0.7,7001\FT].[master].[dbo].[PROVEEDORES]
		)A
	LEFT JOIN
		(
			SELECT * FROM  [FT].[dbo].[IDENTIDADES] WHERE ID_PROV IS NOT NULL AND TIPO = 'PROVEEDOR'
		)B
	ON A.PROVEED = B.ID_PROV
	WHERE B.ID_PROV IS NULL
--//////////////////////////////////////////////////////////////--