-- Ctrl + SHIFT+ E PARA EJECUTAR COMANDO
USE FT_BODEGA
USE FT_MAPELO
IF(1=2)BEGIN
-- ? VER COLUMNAS DE TABLA ? --
    SELECT *
        FROM ARTICULOS
            WHERE DESCRIPCION LIKE '%NEBUCOR%'
            -- WHERE GRUPO IN ('SNT')
            -- AND DESCRIPCION LIKE 'ROYAL%'

SELECT  
    ARTICULO,
    DESCRIPCION,
    GRUPO,
    DEPTO,
    EXISTENCIA
    -- ROUND(PCIO_VTA*(1+IEPS/100+IEPS*IVA/10000+IVA/100),2) AS PRECIO_PUBLICO
        FROM [FT_ALMACEN].[DBO].[ART]
            WHERE GRUPO IN ('ALMA')
            AND EXISTENCIA > '0'
END
