SELECT
--FECHA_HORA,
--SUCURSAL,
ARTICULO,
DESCRIPCION,
SUM(CANTIDAD) AS TOTAL,
PCIO_VTA,
PROMOCION
  FROM [FT].[dbo].[MOVIMIENTOS]
  WHERE TIPO = 'VENTA'
  AND PROMOCION = 'CIRCULO_SALUD_ORO'
  GROUP BY ARTICULO,DESCRIPCION,PCIO_VTA,PROMOCION
  ORDER BY TOTAL DESC
