-- CONSULTA MORTAL PARA COMPARAR TRASPASOS DE TODAS LAS SUCURSALES PORTAL VS PVWIN

USE [BIT]

DECLARE @ORIGEN AS NVARCHAR(50) = 'ALMACEN'

DECLARE @PVWIN_MOVANIO AS TABLE (
	FOLIO_PORTAL INT,
	TRANSAC NVARCHAR(50),
	REFERENCIA NVARCHAR(50),
	F_MOVIM DATE,
	H_ULT_ACT TIME,
	NUM_PZS_ENTRADA FLOAT,
	CAJERO NVARCHAR(50),
	DESC_MOV NVARCHAR(100)
)

DECLARE @TABLA_RESULTADOS AS TABLE (
	USUARIO NVARCHAR(50),
	TIPO NVARCHAR(50),
	FOLIO INT,
	FECHA_HORA DATETIME,
	ORIGEN NVARCHAR(50),
	DESTINO NVARCHAR(50),
	NUM_PZS FLOAT,
	NUM_FILAS FLOAT,
	COMENTARIOS NVARCHAR(100),
	FOLIO_PORTAL INT,
	TRANSAC NVARCHAR(50),
	REFERENCIA NVARCHAR(50),
	F_MOVIM DATE,
	H_ULT_ACT TIME,
	NUM_PZS_ENTRADA FLOAT,
	CAJERO NVARCHAR(50),
	DESC_MOV NVARCHAR(100)
)

IF(1=1)BEGIN
		DECLARE @EMPRESA NVARCHAR(50) = 'FT'
		DECLARE @DESTINO_A NVARCHAR(50)
		DECLARE @SQL_A AS NVARCHAR(50)
		DECLARE @SQL_INSTANCIA_A AS NVARCHAR(50)

		DECLARE @CURSOR_SUCURSALES CURSOR
		SET @CURSOR_SUCURSALES = CURSOR FOR
			SELECT SUCURSAL, SQL, SQL_INSTANCIA
			FROM SUCURSALES
			WHERE EMPRESA = 'FT'
				AND TIPO IN ('SUCURSAL')
				AND STATUS = '1'
				--AND SUCURSAL NOT IN('SANJOSE')
				--AND SUCURSAL IN('MAPELO')
		OPEN @CURSOR_SUCURSALES FETCH NEXT
		FROM @CURSOR_SUCURSALES INTO @DESTINO_A, @SQL_A, @SQL_INSTANCIA_A
		WHILE @@FETCH_STATUS = 0
			BEGIN
				INSERT INTO @PVWIN_MOVANIO
				EXEC('
					SELECT
						SUBSTRING(DESC_MOV, 16, 50) AS FOLIO_PORTAL,
						TRANSAC,
						REFERENCIA,
						F_MOVIM,
						H_ULT_ACT, 
						SUM(CANTIDAD) AS NUM_PZS_ENTRADA,
						CAJERO,
						DESC_MOV
					FROM ['+@SQL_A+'\'+@SQL_INSTANCIA_A+'].[MASTER].[DBO].[MOVANIO]
					WHERE TRANSAC = ''te''
					AND DESC_MOV LIKE ''%PORTAL%''
					GROUP BY
						TRANSAC,
						REFERENCIA,
						F_MOVIM,
						H_ULT_ACT,
						CAJERO,
						DESC_MOV
				')
				INSERT INTO @TABLA_RESULTADOS
				SELECT A.*, B.* FROM
					(
						SELECT
							USUARIO,
							TIPO,
							FOLIO,
							FECHA_HORA,
							ORIGEN,
							DESTINO,
							SUM(CANTIDAD) AS NUM_PZS,
							COUNT(ARTICULO) AS NUM_FILAS,
							COMENTARIOS
						FROM [FT].[dbo].[MOVIMIENTOS]
						WHERE
							MONTH(FECHA_HORA) = MONTH(GETDATE())
							AND YEAR(FECHA_HORA) = YEAR(GETDATE())
							AND TIPO IN ('TRASPASO_ENTRADA', 'TRASPASO_SALIDA', 'TRASPASO_ENTRADA_AJUSTADO')
							AND ORIGEN = @ORIGEN
							AND DESTINO = @DESTINO_A
						GROUP BY
							USUARIO,
							TIPO,
							FOLIO,
							FECHA_HORA,
							ORIGEN,
							DESTINO,
							COMENTARIOS
					)A
				LEFT JOIN
					(
						SELECT * FROM @PVWIN_MOVANIO
					)B
				ON A.FOLIO = B.FOLIO_PORTAL
			FETCH NEXT FROM @CURSOR_SUCURSALES INTO @DESTINO_A, @SQL_A, @SQL_INSTANCIA_A
			END
		CLOSE @CURSOR_SUCURSALES
		DEALLOCATE @CURSOR_SUCURSALES
		SELECT * FROM @TABLA_RESULTADOS
		ORDER BY FECHA_HORA DESC
	END
-- *************************************************************** --
--CONSULTA PARA COMPROBAR TRASPASOS REPETIDOS DIRECTA A MASTER PVWIN
	IF(1=2)BEGIN
		SELECT * FROM(
			SELECT
				MAX(REFERENCIA) AS ULTIMA_REFERENCIA,
				MAX(F_MOVIM) AS ULTIMA_FECHA,
				DESC_MOV,
				COUNT(REFERENCIA) AS REPETICION,
				NUM_PZS
			FROM
				(
					SELECT
						TRANSAC,
						REFERENCIA,
						F_MOVIM,
						SUM(CANTIDAD) AS NUM_PZS,
						DESC_MOV
					FROM MOVANIO
					WHERE TRANSAC = 'te'
					GROUP BY
						TRANSAC,
						REFERENCIA,
						F_MOVIM,
						DESC_MOV
				)TRASPASOS
			GROUP BY
				DESC_MOV,
				NUM_PZS
		)FILTRADA
		WHERE REPETICION > 1
		--AND DESC_MOV LIKE '%PORTAL%'
		ORDER BY REPETICION DESC
	END
-- *************************************************************** --
-- CONSULTA A SFT PARA COMPARAR TRASPASOS PORTAL VS PVWIN
	IF(1=2)BEGIN
		DECLARE @DESTINO AS NVARCHAR(50) = 'CENTRO'
		DECLARE @SQL AS NVARCHAR(50) = 'ft-centro.ddns.net,2001'
		DECLARE @SQL_INSTANCIA AS NVARCHAR(50) = 'SQLEXPRESS'
		INSERT INTO @PVWIN_MOVANIO
		EXEC('
			SELECT
				SUBSTRING(DESC_MOV, 16, 50) AS FOLIO_PORTAL,
				TRANSAC,
				REFERENCIA,
				F_MOVIM,
				H_ULT_ACT,
				SUM(CANTIDAD) AS NUM_PZS,
				DESC_MOV
			FROM ['+@SQL+'\'+@SQL_INSTANCIA+'].[MASTER].[DBO].[MOVANIO]
			WHERE TRANSAC = ''te''
			AND DESC_MOV LIKE ''%PORTAL%''
			GROUP BY
				TRANSAC,
				REFERENCIA,
				F_MOVIM,
				H_ULT_ACT,
				DESC_MOV
		')

		SELECT * FROM
			(
				SELECT TOP 30
					TIPO,
					FOLIO,
					FECHA_HORA,
					ORIGEN,
					DESTINO,
					SUM(CANTIDAD) AS NUM_PZS,
					COMENTARIOS
				FROM [FT].[dbo].[MOVIMIENTOS]
				WHERE
					TIPO IN ('TRASPASO_ENTRADA', 'TRASPASO_SALIDA')
					AND ORIGEN = @ORIGEN
					AND DESTINO = @DESTINO
				GROUP BY
					TIPO,
					FOLIO,
					FECHA_HORA,
					ORIGEN,
					DESTINO,
					COMENTARIOS
		
			)A
		LEFT JOIN
			(
				SELECT * FROM @PVWIN_MOVANIO
			)B
		ON A.FOLIO = B.FOLIO_PORTAL
		ORDER BY A.FECHA_HORA DESC
	END
-- *************************************************************** --