--03 DE FEBRERO DE 2018
--UPDATE PARA RECUPERAR MINIMOS Y MAXIMOS EN PVWIN CON ALGUN RESPALDO HACIENDO COMPARACION POR CODIGO
--NOTA: EL UPDATE SOLO ME FUNCIONA SI LO HAGO CON OPENROWSET, DE LO CONTRARIO ME DICE QUE LA CONSULTA ES DEMASIADO COMPLEJA
	
    -- -IMPORTANTE---
    --SE DEBE COPIAR DE UN RESPALDO DEL ARTICULO DONDE LOS MINIMOS Y MAXIMOS ESTAN BIEN EN _PVW\001 Y RENOMBRAR COMO RESART

--PARA COMPROBAR MINIMOS Y MAXIMOS "ARTICULO" VS "RESART":
	SELECT ARTICULO, MINIMO, MAXIMO FROM [PVWIN]...ARTICULO WHERE ARTICULO = '16'
	SELECT ARTICULO, MINIMO, MAXIMO FROM [PVWIN]...RESART WHERE ARTICULO = '16'
--------------------------------------------------------
--PARA HACER EL UPDATE DE LOS MINIMOS Y MAXIMOS DESDE EL RESAPALDO "RESART"
	UPDATE ARTICULO
		SET
			ARTICULO.MINIMO = RESPALDO.MINIMO,
			ARTICULO.MAXIMO = RESPALDO.MAXIMO
		FROM
			(
				SELECT ARTICULO, MINIMO, MAXIMO
				FROM OPENROWSET(
					'Microsoft.ACE.OLEDB.12.0',
					'dBase 5.0;Database=c:\_pvw\001',
					'SELECT ARTICULO, MINIMO, MAXIMO FROM ARTICULO'
				)
			)ARTICULO
		JOIN
			(
				SELECT ARTICULO, MINIMO, MAXIMO
				FROM OPENROWSET(
					'Microsoft.ACE.OLEDB.12.0',
					'dBase 5.0;Database=c:\_pvw\001',
					'SELECT ARTICULO, MINIMO, MAXIMO FROM RESART'
				)
			)RESPALDO
		ON ARTICULO.ARTICULO = RESPALDO.ARTICULO