SELECT top 100
	REFERENCIA,
	SUM(IMP_VTA + IMP_IEPS + IMP_IVA)AS TOTAL_TICKET,
	FLOOR(SUM(IMP_VTA + IMP_IEPS + IMP_IVA) /50)AS ESTAMPILLAS,
	FLOOR(SUM(IMP_VTA + IMP_IEPS + IMP_IVA) /500)AS BOLETOS

FROM [PVWIN]...[movanio]
WHERE TRANSAC IN ('vt','fv','rv')
AND F_MOVIM
GROUP BY REFERENCIA


SELECT top 100
	CAJERO,
	
	SUM(IMP_VTA + IMP_IEPS + IMP_IVA)AS TOTAL_TICKET,
	FLOOR(SUM(IMP_VTA + IMP_IEPS + IMP_IVA) /50)AS ESTAMPILLAS,
	FLOOR(SUM(IMP_VTA + IMP_IEPS + IMP_IVA) /500)AS BOLETOS

FROM [PVWIN]...[movanio]
WHERE TRANSAC IN ('vt','fv','rv')
GROUP BY CAJERO

SELECT TOP 10*
FROM [PVWIN]...[movanio]


GO


