USE [BIT]

EXEC [BIT].[dbo].[00_PVWIN]
    @SOLICITUD = 'SALIDAS_PREMIOS',
    @EMPRESA = 'FT',
    @SUCURSAL = 'ACATIC'
EXEC [BIT].[dbo].[00_PVWIN]
    @SOLICITUD = 'SALIDAS_PREMIOS',
    @EMPRESA = 'FT',
    @SUCURSAL = 'CAPILLA'

EXEC [BIT].[dbo].[00_PVWIN]
    @SOLICITUD = 'SALIDAS_PREMIOS',
    @EMPRESA = 'FT',
    @SUCURSAL = 'LAMANGA'
EXEC [BIT].[dbo].[00_PVWIN]
    @SOLICITUD = 'SALIDAS_PREMIOS',
    @EMPRESA = 'FT',
    @SUCURSAL = 'MEZCALA'

EXEC [BIT].[dbo].[00_PVWIN]
    @SOLICITUD = 'SALIDAS_PREMIOS',
    @EMPRESA = 'FT',
    @SUCURSAL = 'SANIGNACIO'
EXEC [BIT].[dbo].[00_PVWIN]
    @SOLICITUD = 'SALIDAS_PREMIOS',
    @EMPRESA = 'FT',
    @SUCURSAL = 'SANJOSE'

EXEC [BIT].[dbo].[00_PVWIN]
    @SOLICITUD = 'SALIDAS_PREMIOS',
    @EMPRESA = 'FT',
    @SUCURSAL = 'ZAPOTLANEJO'
EXEC [BIT].[dbo].[00_PVWIN]
    @SOLICITUD = 'SALIDAS_PREMIOS',
    @EMPRESA = 'FT',
    @SUCURSAL = 'PEGUEROS'

EXEC [BIT].[dbo].[00_PVWIN]
    @SOLICITUD = 'SALIDAS_PREMIOS',
    @EMPRESA = 'FT',
    @SUCURSAL = 'YAHUALICA'
EXEC [BIT].[dbo].[00_PVWIN]
    @SOLICITUD = 'SALIDAS_PREMIOS',
    @EMPRESA = 'FT',
    @SUCURSAL = 'ARANDAS'