-- -VERIFICACION DIARIA DE VENTAS EN EL PORTAL- --
		-- -RESUMEN- --
			SELECT
				TOP (1000)
				FOLIO,
				MAX(FECHA_HORA) AS FECHA_HORA,
				SUCURSAL,
				USUARIO,
				COUNT(CANTIDAD) AS PIEZAS,
				--SUM(PCIO_VTA*CANTIDAD), AS IMPORTE_SIN_IMPUESTOS,
				ROUND(SUM(CANTIDAD*(([PCIO_VTA]-([PCIO_VTA]*DESCUENTO/100))*(1+[IEPS]/100+[IEPS]*[IVA]/10000+[IVA]/100))),2) AS IMPORTE
			FROM [FT].[dbo].[MOVIMIENTOS]
			WHERE TIPO IN('VENTA','VENTA_CANCELADA')
			AND REFERENCIA IS NULL
			-- AND USUARIO = 'AnaMaria'
			GROUP BY FOLIO, SUCURSAL, USUARIO
			ORDER BY FECHA_HORA DESC
		-- ------------ --

		-- -DETALLES- --
			SELECT
				TOP(1000)
				TIPO,
				FOLIO,
				REFERENCIA,
				FECHA_HORA,
				SUCURSAL,
				USUARIO,
				ARTICULO,
				DESCRIPCION,
				CANTIDAD,
				PCIO_VTA,
				COMENTARIOS,
				PROMOCION
				-- *
			FROM [FT].[dbo].[MOVIMIENTOS]
			WHERE TIPO IN('VENTA')
			-- AND CONVERT(DATE, FECHA_HORA) = '2024-11-22'
			AND SUCURSAL = 'GONZALEZ'
			AND ARTICULO = '7501300420411'
			AND REFERENCIA IS NULL
			
			-- AND USUARIO = 'AnaMaria'
			--AND SUCURSAL = 'CENTRO'
			ORDER BY FECHA_HORA DESC
			 
		-- ------------ --