SELECT
				TOP(2000)
				TIPO,
				FOLIO,
				CANTIDAD,
				ARTICULO,
				DESCRIPCION,
				REFERENCIA,
				FECHA_HORA,
				SUCURSAL,
				USUARIO,
				PCIO_VTA,
				COMENTARIOS,
				PROMOCION
				-- *
			FROM [FT].[dbo].[MOVIMIENTOS]
			WHERE TIPO IN('VENTA','VENTA_CANCELADA')
			AND PROMOCION IS NULL
			-- AND REFERENCIA IS NULL
			-- AND USUARIO = 'AnaMaria'
			-- AND SUCURSAL = 'SANJOSE'
			-- AND SUCURSAL = 'ARANDAS'
			-- AND REFERENCIA LIKE 'PROMOCION_APLICADA_%'
			-- AND CAST(FECHA_HORA AS DATE) = DATEADD(day, -1, CAST(GETDATE() AS DATE))
			ORDER BY FECHA_HORA DESC

----- MISMOS COMENTARIOS CIRCULO MISMOS FOLIOS---
		SELECT
		COUNT(DISTINCT(FOLIO)) AS FOLIOS,
		COMENTARIOS,
		COUNT(COMENTARIOS) AS COMENTARIOSS
			FROM [FT].[dbo].[MOVIMIENTOS]
			WHERE TIPO IN('VENTA','VENTA_CANCELADA')
			AND YEAR(FECHA_HORA) =2024
			GROUP BY COMENTARIOS
			ORDER BY FOLIOS DESC	

---------CONSULTAR COMENTARIOS AGRUPADOS POR SUCURSAL-----------------------------
SELECT 
COUNT(DISTINCT(FOLIO)) AS FOLIOS,
SUCURSAL
FROM [FT].[dbo].[MOVIMIENTOS]
			WHERE TIPO IN('VENTA','VENTA_CANCELADA')
			AND YEAR(FECHA_HORA) =2024
			AND COMENTARIOS =''	--SE ESTA BUSCANDO LA CANTIDAD DE COMENTARIOS VACIOS-
			GROUP BY SUCURSAL
					