----VENTAS PERIODO MAPELO--
SELECT A.*, A.PCIO_VTA*TOTAL AS TOTALVENTA
FROM(SELECT 
      --CONVERT(DATE,[FECHA_HORA]) AS FECHA
      --,[CANTIDAD]
      [ARTICULO]
      ,[DESCRIPCION]
      --,[PCIO_COM]
      ,[PCIO_VTA]
      --,[IEPS]
      --,[IVA]
      ,[DESCUENTO]
	  ,SUM(CANTIDAD) AS TOTAL		
	  
  FROM [FT_MAPELO].[dbo].[MOV]
  WHERE YEAR(FECHA_HORA) = '2024'
  AND TRANSAC IN ('vt','vr','vf')
  GROUP BY ARTICULO,DESCRIPCION,PCIO_VTA,DESCUENTO)A
  ORDER BY TOTALVENTA DESC



  SELECT
  SUM(PCIO_VTA),
  MONTH(FECHA_HORA)
 FROM [FT_MAPELO].[dbo].[MOV]
 WHERE TRANSAC IN ('vt','vr','vf')
 AND YEAR(FECHA_HORA) = '2025'
 GROUP BY MONTH(FECHA_HORA)


------------------------------------------------------------------------------------------------------



USE FT_MAPELO
-- IF(1=2)BEGIN

SELECT TOP 100 *
        FROM [FT_MAPELO].[DBO].[MOV]
SELECT TOP 100 *
        FROM [FT_MAPELO].[DBO].[ART]

-- ? CONSULTA DE REGISTROS DE VENTAS GENERALES? --
SELECT
A.ARTICULO,A.DESCRIPCION,A.[MES], A.[CANTIDAD PATITO],B.EXISTENCIA,B.DEPTO,B.GRUPO 
FROM
 (
    SELECT 
            TRANSAC,
            -- FOLIO,
            -- REFERENCIA,
            YEAR (FECHA_HORA) AS [AÑO],
            MONTH(FECHA_HORA) AS [MES],
            -- DAY(FECHA_HORA) AS [DIA],
            -- SUCURSAL,
            -- USUARIO,
            ARTICULO,
            DESCRIPCION,
            -- PCIO_VTA,
            -- COMENTARIOS,
            SUM (CANTIDAD) AS [CANTIDAD PATITO]
        FROM [FT_MAPELO].[DBO].[MOV]
            WHERE TRANSAC IN ('VT','VR','VF')
            AND YEAR(FECHA_HORA) = 2023
            AND MONTH(FECHA_HORA) = 1
            -- AND DAY(FECHA_HORA) = 16
            AND EXISTENCIA >= '10'
            GROUP BY TRANSAC,ARTICULO, DESCRIPCION,  YEAR (FECHA_HORA), MONTH(FECHA_HORA)
            -- DAY(FECHA_HORA)
            
) A
LEFT JOIN
( 
    SELECT   ARTICULO, EXISTENCIA,DEPTO,GRUPO
    FROM [FT_MAPELO].[DBO].[ART]
    WHERE DEPTO IN('MD','MDA','IMPN')
) B
ON A.ARTICULO = B.ARTICULO
WHERE B.ARTICULO IS NOT NULL
ORDER BY A.[CANTIDAD PATITO] DESC


-- ? CONSULTA DE REGISTROS DE VENTAS ESPECIFICO? --
SELECT
A.ARTICULO,A.DESCRIPCION, A.[CANTIDAD PATITO],B.EXISTENCIA, A.TRANSAC,B.GRUPO FROM
 (
    SELECT 
            TRANSAC,
            -- FOLIO,
            -- REFERENCIA,
            -- YEAR (FECHA_HORA) AS [2022],
            -- SUCURSAL,
            -- USUARIO,
            ARTICULO,
            DESCRIPCION,
            -- PCIO_VTA,
            -- COMENTARIOS,
            SUSELEM (CANTIDAD) AS [CANTIDAD PATITO]
        FROM [FT_MAPELO].[DBO].[MOV]
            WHERE TRANSAC IN ('VT','VR','VF')
            AND YEAR(FECHA_HORA) = '2022'
            AND EXISTENCIA >= '10'
            GROUP BY TRANSAC, ARTICULO, DESCRIPCION
            
) A
LEFT JOIN
( 
    SELECT 
     ARTICULO,
     EXISTENCIA, 
     GRUPO,
     DEPTO
    FROM [FT_MAPELO].[DBO].[ART]
    WHERE GRUPO IN ('BOD')
) B
ON A.ARTICULO = B.ARTICULO
-- WHERE A.ARTICULO = '16' AND A.DESCRIPCION ='A GRANEL AZUCAR STANDAR 950GR'
ORDER BY A.[CANTIDAD PATITO] DESC



-- ?CONSULTA PARA VER VENTAS TICKET POR DIA,MES,AÑO? --
SELECT 
DAY(A.FECHA_HORA)AS DIA, COUNT(DISTINCT(A.REFERENCIA)) AS [TICKETS VENDIDOS]
	FROM 
(
SELECT 
	TRANSAC,
	REFERENCIA,
	ARTICULO,
	FECHA_HORA



	
FROM [FT_MAPELO].[DBO].[MOV]
WHERE TRANSAC IN('VT','VR','VF')

)A
LEFT JOIN
(
SELECT ARTICULO,GRUPO,DEPTO
FROM [FT_MAPELO].[DBO].[ART]
)B

ON A.ARTICULO = B.ARTICULO
WHERE B.DEPTO IN('MD','MDA','IMPN')
AND YEAR(A.FECHA_HORA) = '2023'
AND MONTH(A.FECHA_HORA) = '1'
-- AND DATEPART(HOUR, A.FECHA_HORA) > '15'

GROUP BY DAY(A.FECHA_HORA)


-- END  



 FROM [FT_MAPELO].[DBO].[ART]