-- - PARA EJECUTAR EN LOCAL "SQL COMPU FERNANDA"
USE [BITS]
	--*PRODUCTS_UPDATE_INFO - 02/10/2021 12:15:46 p. m.**********************************************--
		DECLARE @TABLE_PRODUCTS_UPDATE_INFO TABLE_PRODUCTS_UPDATE_INFO
		INSERT INTO @TABLE_PRODUCTS_UPDATE_INFO
		SELECT
			MAPELO.[ARTICULO] AS [SKU],
			MAPELO.[DESCRIPCION] AS [NAME],
			'' AS [BRAND],
			'' AS [DESCRIPTION],
			'' AS [FEATURES],
			'' AS [NOTES]
		FROM
			(
				SELECT
					[SKU]
				FROM PRODUCTS
			)BITS
		FULL JOIN
			(
				SELECT
					[ARTICULO],
					[DESCRIPCION]
				FROM [10.10.1.100,1001\FT].[BIT].[dbo].[V_ART]
				WHERE YEAR([FECHA_HORA]) >= YEAR(GETDATE()) - 1 -- ! SOLO ARTICULOS CON MOVIMIENTOS EN EL AÑO ACTUAL Y EL AÑO ANTERIOR
					AND DEPTO NOT IN('ELIM','20EL','E') -- ! EXCLUIDOS DEPARTAMENTOS DE ELIMINADOS
					AND GRUPO NOT IN('ELIM','20EL','E')	-- ! EXCLUIDOS GRUPOS DE ELIMINADOS
			)MAPELO
		ON BITS.[SKU] = MAPELO.[ARTICULO] COLLATE SQL_Latin1_General_CP1_CI_AS -- ! IMPORTANTE EL COLATE PARA Q COMPARE BIEN
		-- WHERE BITS.[SKU] IS NULL
		WHERE MAPELO.ARTICULO IS NOT NULL

		EXEC [BITS].[DBO].[ADMIN_PROCEDURES]
			@REQUEST = 'PRODUCTS_UPDATE_INFO',
			@TABLE_PRODUCTS_UPDATE_INFO = @TABLE_PRODUCTS_UPDATE_INFO
		SELECT 'PRODUCTS_UPDATE_INFO FINISHED' AS FINISH
		GO
	--***********************************************************************************************--
	--*PRODUCTS_UPDATE_PRICES - 22/11/2021 02:10:04 a. m.********************************************--
		DECLARE @TABLE_PRODUCTS_UPDATE_PRICES TABLE_PRODUCTS_UPDATE_PRICES
		INSERT INTO @TABLE_PRODUCTS_UPDATE_PRICES
		SELECT
			[ARTICULO],
			[PCIO_VTA],
			[IVA],
			[IEPS],
			[DESCUENTO],
			CONVERT(DATE, [VIGENCIA]) AS [VIGENCIA],
			CONVERT(DATE, [CADUCIDAD]) AS [CADUCIDAD]
		FROM [10.10.1.100,1001\FT].[BIT].[dbo].[V_ART]
		WHERE YEAR([FECHA_HORA]) >= YEAR(GETDATE()) - 1 -- ! SOLO ARTICULOS CON MOVIMIENTOS EN EL AÑO ACTUAL Y EL AÑO ANTERIOR
			AND DEPTO NOT IN('ELIM','20EL','E') -- ! EXCLUIDOS DEPARTAMENTOS DE ELIMINADOS
			AND GRUPO NOT IN('ELIM','20EL','E')	-- ! EXCLUIDOS GRUPOS DE ELIMINADOS
		EXEC [BITS].[DBO].[ADMIN_PROCEDURES]
			@REQUEST = 'PRODUCTS_UPDATE_PRICES',
			@TABLE_PRODUCTS_UPDATE_PRICES = @TABLE_PRODUCTS_UPDATE_PRICES
		SELECT 'PRODUCTS_UPDATE_PRICES FINISHED' AS FINISH
		GO
	--***********************************************************************************************--
	--*STOCK_UPDATE - 03/10/2021 02:02:57 a. m.******************************************************--
		DECLARE @TABLE_STOCK TABLE_STOCK_UPDATE
		INSERT INTO @TABLE_STOCK
		SELECT
				'MAPELO' AS [BRANCH],
				ARTICULO AS [SKU],
				EXISTENCIA AS [STOCK],
				GETDATE() AS [DATE]
		FROM [10.10.1.100,1001\FT].[BIT].[dbo].[V_ART]
		WHERE YEAR([FECHA_HORA]) >= YEAR(GETDATE()) - 1 -- ! SOLO ARTICULOS CON MOVIMIENTOS EN EL AÑO ACTUAL Y EL AÑO ANTERIOR
			AND DEPTO NOT IN('ELIM','20EL','E') -- ! EXCLUIDOS DEPARTAMENTOS DE ELIMINADOS
			AND GRUPO NOT IN('ELIM','20EL','E')	-- ! EXCLUIDOS GRUPOS DE ELIMINADOS
		EXEC [BITS].[DBO].[ADMIN_PROCEDURES]
			@REQUEST = 'STOCK_UPDATE',
			@TABLE_STOCK_UPDATE = @TABLE_STOCK
		SELECT 'STOCK_UPDATE FINISHED' AS FINISH
		GO
		--*MASTER STOCK UPDATE - 05/10/2022 06:41:32 PM ***********************************************--
			EXEC [BITS].[DBO].[ADMIN_PROCEDURES]
				@REQUEST = 'MASTER_STOCK_UPDATE'
			SELECT 'MASTER_STOCK_UPDATE FINISHED' AS FINISH
			GO
		--*********************************************************************************************--
	--***********************************************************************************************--
	--*PRODUCTS_UPDATE_RANKING - 18/12/2021 09:26:31 p. m.*******************************************--
		DECLARE @TABLE_PRODUCTS_UPDATE_RANKING TABLE_PRODUCTS_UPDATE_RANKING
		DECLARE @CANTIDAD_DE_ARTICULOS AS FLOAT = (SELECT COUNT(ARTICULO) FROM [10.10.1.100,1001\FT].[BIT].[dbo].[ARTICULO])
		INSERT INTO @TABLE_PRODUCTS_UPDATE_RANKING
		SELECT
			[ARTICULO],
			FLOOR(
				ROW_NUMBER() OVER(
					ORDER BY
						SAL_AF ASC,
						F_ULT_SAL ASC,
						INV_INI ASC
				) / @CANTIDAD_DE_ARTICULOS * 100
			) AS RANKING
		FROM [10.10.1.100,1001\FT].[BIT].[dbo].[ARTICULO]
		WHERE DEPTO != 'ELIM' -- 7764 PRODUCTOS
			AND GRUPO != 'ELIM' 	-- 101	PRODUCTOS
			AND DEPTO != '20EL' 	-- 77		PRODUCTOS
			AND GRUPO != 'E' 			-- 1136 PRODUCTOS
			AND DEPTO != 'E' 			-- 1206 PRODUCTOS
		EXEC [BITS].[DBO].[ADMIN_PROCEDURES]
			@REQUEST = 'PRODUCTS_UPDATE_RANKING',
			@TABLE_PRODUCTS_UPDATE_RANKING = @TABLE_PRODUCTS_UPDATE_RANKING
		SELECT 'PRODUCTS_UPDATE_RANKING FINISHED' AS FINISH
		GO
	--***********************************************************************************************--
	--*PRODUCTS_UPDATE_REWARDS - 18/12/2021 09:26:31 p. m.*******************************************--
		DECLARE @TABLE_PRODUCTS_UPDATE_REWARDS TABLE_PRODUCTS_UPDATE_REWARDS
		INSERT INTO @TABLE_PRODUCTS_UPDATE_REWARDS
		SELECT
			[ARTICULO],
			[PUNTOS_PREMIO],
			[EFECTIVO_PREMIO]
		FROM [10.10.0.102,1000\FT].[FT].[dbo].[ARTICULOS]
		WHERE [EDICION] <> 0
		AND [PUNTOS_PREMIO] > 0
		EXEC [BITS].[DBO].[ADMIN_PROCEDURES]
			@REQUEST = 'PRODUCTS_UPDATE_REWARDS',
			@TABLE_PRODUCTS_UPDATE_REWARDS = @TABLE_PRODUCTS_UPDATE_REWARDS
		SELECT 'PRODUCTS_UPDATE_REWARDS FINISHED' AS FINISH
		GO
	--***********************************************************************************************--