-- - PARA EJECUTAR EN FARMACIATEPA.COM.MX
		USE [BITS]
	--*PRODUCTS_UPDATE_INFO - 02/10/2021 12:15:46 p. m.**********************************************--
		DECLARE @TABLE_PRODUCTS_UPDATE_INFO TABLE_PRODUCTS_UPDATE_INFO
		INSERT INTO @TABLE_PRODUCTS_UPDATE_INFO
		SELECT
			[SKU],
			[NAME],
			[BRAND],
			[DESCRIPTION],
			[FEATURES],
			[NOTES]
		FROM [FT-MAPELO.DDNS.NET,3391\FTEXPRESS].[BITS].[dbo].[PRODUCTS]
		WHERE ISNULL([STATUS],'') != 'D'
		EXEC [BITS].[DBO].[ADMIN_PROCEDURES]
			@REQUEST = 'PRODUCTS_UPDATE_INFO',
			@REPLACE_NAME = 1,
			@TABLE_PRODUCTS_UPDATE_INFO = @TABLE_PRODUCTS_UPDATE_INFO
		SELECT 'PRODUCTS_UPDATE_INFO FINISHED' AS FINISH
		GO
	--***********************************************************************************************--
	--*PRODUCTS_UPDATE_PRICES - 22/11/2021 02:10:04 a. m.********************************************--
		DECLARE @TABLE_PRODUCTS_UPDATE_PRICES TABLE_PRODUCTS_UPDATE_PRICES
		INSERT INTO @TABLE_PRODUCTS_UPDATE_PRICES
		SELECT
			[SKU],
			[PRICE_UNIT],
			[IVA],
			[IEPS],
			[DISCOUNT],
			[DISCOUNT_START],
			[DISCOUNT_END]
		FROM [FT-MAPELO.DDNS.NET,3391\FTEXPRESS].[BITS].[dbo].[PRODUCTS]
		EXEC [BITS].[DBO].[ADMIN_PROCEDURES]
			@REQUEST = 'PRODUCTS_UPDATE_PRICES',
			@TABLE_PRODUCTS_UPDATE_PRICES = @TABLE_PRODUCTS_UPDATE_PRICES
		SELECT 'PRODUCTS_UPDATE_PRICES FINISHED' AS FINISH
		GO
	--***********************************************************************************************--
	--*STOCK_UPDATE - 03/10/2021 02:02:57 a. m.******************************************************--
		DECLARE @TABLE_STOCK TABLE_STOCK_UPDATE
		INSERT INTO @TABLE_STOCK
			  SELECT * FROM [FT-MAPELO.DDNS.NET,3391\FTEXPRESS].[BITS].[dbo].[STOCK_PRODUCTS] -- 22/04/2024 01:18:46 PM - SE CAMBIÓ POR VISTA, VER EN VISTAS DE FERNANDA
		EXEC [BITS].[DBO].[ADMIN_PROCEDURES]
			@REQUEST = 'STOCK_UPDATE',
			@TABLE_STOCK_UPDATE = @TABLE_STOCK
		SELECT 'STOCK_UPDATE FINISHED' AS FINISH
		GO
		--*MASTER STOCK UPDATE - 05/10/2022 06:41:32 PM ***********************************************--
			EXEC [BITS].[DBO].[ADMIN_PROCEDURES]
				@REQUEST = 'MASTER_STOCK_UPDATE'
			SELECT 'MASTER_STOCK_UPDATE FINISHED' AS FINISH
			GO
		--*********************************************************************************************--
	--***********************************************************************************************--
	--*PRODUCTS_UPDATE_RANKING - 18/12/2021 09:26:31 p. m.*******************************************--
		DECLARE @TABLE_PRODUCTS_UPDATE_RANKING TABLE_PRODUCTS_UPDATE_RANKING
		INSERT INTO @TABLE_PRODUCTS_UPDATE_RANKING
		SELECT
			[SKU],
			[RANKING]
		FROM [FT-MAPELO.DDNS.NET,3391\FTEXPRESS].[BITS].[dbo].[PRODUCTS]
		EXEC [BITS].[DBO].[ADMIN_PROCEDURES]
			@REQUEST = 'PRODUCTS_UPDATE_RANKING',
			@TABLE_PRODUCTS_UPDATE_RANKING = @TABLE_PRODUCTS_UPDATE_RANKING
		SELECT 'PRODUCTS_UPDATE_RANKING FINISHED' AS FINISH
		GO
	--***********************************************************************************************--
	--*PRODUCTS_UPDATE_REWARDS - 18/12/2021 09:26:31 p. m.*******************************************--
		DECLARE @TABLE_PRODUCTS_UPDATE_REWARDS TABLE_PRODUCTS_UPDATE_REWARDS
		INSERT INTO @TABLE_PRODUCTS_UPDATE_REWARDS
		SELECT
			[SKU],
			[PRIZE_POINTS],
			[PRIZE_CASH]
		FROM [FT-MAPELO.DDNS.NET,3391\FTEXPRESS].[BITS].[dbo].[PRODUCTS]
		WHERE [PRIZE_POINTS] > 0
		EXEC [BITS].[DBO].[ADMIN_PROCEDURES]
			@REQUEST = 'PRODUCTS_UPDATE_REWARDS',
			@TABLE_PRODUCTS_UPDATE_REWARDS = @TABLE_PRODUCTS_UPDATE_REWARDS
		SELECT 'PRODUCTS_UPDATE_REWARDS FINISHED' AS FINISH
		GO
	--***********************************************************************************************--