USE [BITS]
	--30/12/2020 09:38:59 p. m. - CONSULTAS PARA OPERACIONES EN FOTOS CON LA FINALIDAD DE SUBIR FOTOS LOCALES A CLOUDINARY
IF (1=2) BEGIN
	-- * PRIMERO CREAR FUNCION QUE SE GUARDA EN PROGRAMACION->FUNCIONES DE LA BASE DE DATOS ACTUAL * //
		-- ? ES PARA EVALUAR SI EXISTE O NO UN ARCHIVO - 30/12/2020 08:53:29 p. m. ? //
			-- CREATE FUNCTION dbo.fn_FileExists(@path varchar(512))
			-- RETURNS BIT
			-- AS
			-- BEGIN
			-- 	 DECLARE @result INT
			-- 	 EXEC master.dbo.xp_fileexist @path, @result OUTPUT
			-- 	 RETURN cast(@result as bit)
			-- END;
			-- GO

	-- * DESPUES INSERT DE CONTENIDO DE LA CARPETA EN LA TABLA PHOTOS * //
		DECLARE @ROOT AS NVARCHAR(50) = 'R:\FOTOS ARTICULOS FT\FHD\MINI\';
		-- DECLARE @TERMINACION AS NVARCHAR(50) = '.jpg'
		DECLARE @TERMINACION AS NVARCHAR(50) = '_01.jpg'
		INSERT INTO [BITS].[dbo].[PHOTOS]
			(
				[SKU],
				[URL],
				[FILE]
			)
		SELECT INSRT.* FROM
			(
				SELECT
					SKU,
					CONVERT(varchar(50), NEWID()) AS [URL],	-- ? PARA GENERAR UN ID ALEATORIO Y UTILIZARLO EN CLOUDINARY ? --
					CONCAT(SKU,@TERMINACION) AS [FILE]
				FROM PRODUCTS
				WHERE dbo.fn_FileExists(CONCAT(@ROOT,SKU,@TERMINACION)) > 0
			)INSRT
		LEFT JOIN
			(
				SELECT
					[FILE]
				FROM PHOTOS
			)PHOTOS
		ON INSRT.[FILE] = PHOTOS.[FILE]
		WHERE PHOTOS.[FILE] IS NULL

	-- * PASANDO DATOS DE FOTOS DE LOCAL A LA TABLA PHOTOS DE LA NUBE GCP CON SERVIDOR VINCULADO -- NOTA: MUY LENTO, DURÓ: 5 min. CON ~3000 FILAS EL 31/12/2020 01:13:03 a. m.
		-- ? 19/12/2021 02:21:01 p. m.: DONT WORRY I NOW HAVE A TOO MUCH BETTER SOLUTION WITH MERGE METHODS
		-- TODO: MERGE METHOD TO UPLOAD
		-- INSERT INTO [35.223.216.34].[BITS].[dbo].[PHOTOS]
		-- 	(
		-- 		[SKU],
		-- 		[URL],
		-- 		[FILE]
		-- 	)
		-- SELECT
		-- 		[SKU],
		-- 		[URL],
		-- 		[FILE]
		--   FROM [BITS].[dbo].[PHOTOS]

	-- TODO: DISABLE BANNERS CHANGING TYPE
		-- 'INACTIVE_BANNER_TOP_HOME' AS [TYPE]

	-- TODO: TO INSERT BANNERS INFORMATION IN THE TABLE "IMAGES"
		-- ! PREFERENTEMENTE PONER NOMBRE DEL BANNER DE LA SIGUIENTE MANERA:
			-- ! banner_yymmdd_n.png ! --
			-- ! ejemplo: banner_211231_1.png ! --
			-- ! ejemplo: banner_211231_2.png ! --
		DECLARE @TOTAL_IMAGES_TO_UPLOAD AS INT = 7; -- ? NUMERO DE IMAGENES A SUBIR ? --
		DECLARE @DATE_START AS DATE = '2021-12-15'; -- ? NUMERO DE IMAGENES A SUBIR ? --
		DECLARE @DATE_END AS DATE = '2021-12-18'; -- ? NUMERO DE IMAGENES A SUBIR ? --
		DECLARE @TYPE AS NVARCHAR(40) = 'BANNER_TOP_HOME'; -- ? TIPO DE BANNER PARA SINCRONIA CON EL FRONTEND ? --
		DECLARE @ID_PREFIX AS NVARCHAR(48) = 'banner_211219_'; -- ? PREFIJO DE LAS IMAGENES A SUBIR ? --
		DECLARE @EXTENCION AS NVARCHAR(4) = '.png'; -- ? NUMERO DE IMAGENES A SUBIR ? --
		DECLARE @ROOT_IMAGES_FOLDER AS NVARCHAR(50) = 'i:\COM\FT\DESIGN\PNG\'; -- ? RUTA DE LA CARPETA DONDE ESTAN LAS IMAGENES ? --
		-- DECLARE @DISABLE_OTHERS AS BIT = 0; -- ? EN 0 PARA NO DESHABLITAR OTROS DEL MISMO TIPO ? --
		DECLARE @DISABLE_OTHERS AS BIT = 1; -- ? EN 1 PARA DESHABLITAR OTROS DEL MISMO TIPO ? --

		-- ? PRIMERO PARA DESHABILITAR IMAGENES/PUBLICIDADES ANTERIORES ? --
			IF(@DISABLE_OTHERS > 0) BEGIN
				UPDATE [BITS].[dbo].[IMAGES] SET
					[ID] = CONCAT('DISABLED_',[ID]),
					[TYPE] = CONCAT('DISABLED_',[TYPE])
				WHERE [TYPE] = @TYPE
			END;
		-- ? DESPUES INSERTAR NUEVAS IMAGENES/PUBLICIDADES ? --

			DECLARE @I INT = 0;
			WHILE @I < @TOTAL_IMAGES_TO_UPLOAD
			BEGIN
				SET @I = @I + 1;
				INSERT INTO [BITS].[dbo].[IMAGES]
					(
						[ID],
						[TYPE],
						[URL],
						[FILE],
						[DATE_START],
						[DATE_END]
					)
				VALUES
					(
						CONCAT(@ID_PREFIX, @I), -- AS [ID],
						@TYPE, -- AS [TYPE],
						CONVERT(varchar(50), NEWID()), -- AS [URL],	-- ? PARA GENERAR UN ID ALEATORIO Y UTILIZARLO EN CLOUDINARY ? --
						CONCAT(@ID_PREFIX, @I, @EXTENCION), -- AS [FILE]
						@DATE_START,
						@DATE_END
					)
			END;

	

	
		-- SELECT convert(char, getdate(), 12) --? FORMATO: yymmdd "211231" ?--
END